jobs:
  include:
    - language: node_js
      node_js: 
        - 13
      services: 
        - docker
      script:
        - docker --version
        - cd udagram-feed
        - docker build -t udagram-feed .
        - docker tag udagram-feed $DOCKER_USERNAME/udagram-feed
      
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/udagram-feed

    - language: node_js
      node_js: 
        - 13
      services: 
        - docker
      script:
        - docker --version
        - cd udagram-users
        - docker build -t udagram-users .
        - docker tag udagram-users $DOCKER_USERNAME/udagram-users
      
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/udagram-users

    - language: minimal
      services: 
        - docker
      script:
        - docker --version
        - cd udagram-frontend
        - npm -v
        - node -v
        - docker build -t udagram-frontend .
        - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend
      
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/udagram-frontend
