apiVersion: v1
kind: Service
metadata:
  labels:
    service: front
  name: front
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: front
  type: LoadBalancer
